export const GET_ALL = 'GET_ALL';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const SEARCH_NAME = 'SEARCH_NAME';
export const ORDER_BY_NAME = "FILTER_BY_NAME"; 
export const FILTER_BY_BRAND = "FILTER_BY_BRAND";
export const REFRESH = "REFRESH";
export const FILTER = "FILTER"
export const GET_ALL_BRANDS = "GET_ALL_BRANDS"
export const SET_SELECTED_BRAND = "SET_SELECTED_BRAND"
export const FILTER_BRAND_AND_PRICE = "FILTER_BRAND_AND_PRICE"
export const SET_PRODUCT_RATING = "SET_PRODUCT_RATING"

